### ISSUE TITLE
Internal gRPC  error

### ISSUE THREAD

**Issue by treb0r** [nymtech/nym-vpn-client#1526] opened 2024-11-11 16:00 UTC
I installed NYM-VPN on Ubuntu 24.10. Every time I try to add the credentials I see:

Internal gRPC  error

Client version 0.2.3
Daemon version 1.0.0-dev
Network mainnet

Ubuntu 24.10
Gnome  27
Wayland
Linux 6.11.0-9-generic

**Comment by marcdbz** [comment] 2024-11-15 11:55
Hi thanks for sharing, this is a known issue. We are looking into this, but may not fix it: We have a new credential system around the corner. This will be based on zero-knowledge proofs for better privacy properties.

**Comment by doums** [comment] 2024-11-15 13:05
The issue is @treb0r you're running a daemon not compatible with the 0.2.3 client, the one you want is https://github.com/nymtech/nym-vpn-client/releases/tag/nym-vpn-core-v0.2.4

**Comment by doums** [comment] 2024-11-15 13:06
Closing the issue, please feel free to re-open it, if you hit another blocking issue

**Closed by doums** 2024-11-15 13:06 UTC
